/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import com.mysql.cj.conf.PropertyKey;
import com.sun.jdi.connect.spi.Connection;
import com.toedter.calendar.JDateChooser;
import controller.CustomerController;
import controller.ReservationController;
import controller.RoomController;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.Date;
import model.CustomerModel;
import model.ReservationModel;
import model.RoomModel;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperFillManager;




/**
 *
 * @author tharaka
 */
public class Dashboard extends javax.swing.JFrame {

      private RoomController roomController1;
      private CustomerController customerController1;
      
      private ReservationController reController1;
      private ArrayList<RoomModel> roomsRE;
      private ArrayList<ReservationModel> reservations;
      
      private boolean isAddReservation = true;
    
      public Dashboard() {
        initComponents();
        roomController1 = new RoomController();
        RoomModel roomModel1 = new RoomModel();
        roomController1.connect(roomModel1);
        roomController1.autoID(roomModel1, lbl_rID);
        roomController1.loadRoom(tbl_room, roomModel1);
        
        customerController1 = new CustomerController();
        CustomerModel customerModel1 = new CustomerModel();
        customerController1.connect(customerModel1);
        customerController1.loadCustomer(tbl_customer, customerModel1);
        
        reController1 = new ReservationController();
        ReservationModel reModel1 = new ReservationModel();
        reController1.connect(reModel1);
        reController1.autoID(reModel1, lbl_reID);
        reController1.loadRoomType(cmb_roomTypeRE);
        reController1.loadBedType(cmb_bedTypeRE);
        
        initializeTimer();
        
//        reController1.loadReservation(tbl_reservation, reModel1);

        reservations = reController1.getReservations();
        
        Iterator it = reservations.iterator();
        while (it.hasNext()){
            ReservationModel rModel = (ReservationModel)it.next();
            DefaultTableModel d = (DefaultTableModel) tbl_reservation.getModel();
            d.addRow(new Object[]{rModel.getId(), rModel.getCustomer_nic(), rModel.getRoom_roomID(), rModel.getCheckin(), rModel.getCheckout(), rModel.getAmount()});
        }
        
        date_checkInRE.setMinSelectableDate(new Date());
        var localDate = java.time.LocalDateTime.now().plusDays(1);
        Date date = java.util.Date.from(localDate
      .atZone(ZoneId.systemDefault())
      .toInstant());
        
        date_checkOutRE.setMinSelectableDate(date);
    }
      
      Connection con;
      PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        side_panel = new javax.swing.JPanel();
        pnl_roomBTN = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_cusBTN = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnl_resBTN = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_homeBTN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_reportsBTN1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        lbl_SysDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_roomNo = new javax.swing.JLabel();
        lbl_rID = new javax.swing.JLabel();
        lbl_roomType = new javax.swing.JLabel();
        cmb_roomType = new javax.swing.JComboBox<>();
        lbl_bedType = new javax.swing.JLabel();
        cmb_bedType = new javax.swing.JComboBox<>();
        lbl_amount = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_room = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_roomNo2 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        lbl_roomNo1 = new javax.swing.JLabel();
        txt_cusName = new javax.swing.JTextField();
        btn_addCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_customer = new javax.swing.JTable();
        btn_editCustomer = new javax.swing.JButton();
        btn_deleteCustomer = new javax.swing.JButton();
        btn_clearCustomer = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        cmb_gender = new javax.swing.JComboBox<>();
        lbl_roomNo5 = new javax.swing.JLabel();
        lbl_roomNo3 = new javax.swing.JLabel();
        txt_mobile = new javax.swing.JTextField();
        txt_cusAddress = new javax.swing.JTextField();
        lbl_roomNo4 = new javax.swing.JLabel();
        lbl_roomNo6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_roomNo7 = new javax.swing.JLabel();
        lbl_reID = new javax.swing.JLabel();
        lbl_roomNo8 = new javax.swing.JLabel();
        txt_nameRE = new javax.swing.JTextField();
        lbl_roomNo9 = new javax.swing.JLabel();
        txt_nicRE = new javax.swing.JTextField();
        lbl_roomNo10 = new javax.swing.JLabel();
        cmb_roomTypeRE = new javax.swing.JComboBox<>();
        btn_addRE = new javax.swing.JButton();
        btn_editRE = new javax.swing.JButton();
        btn_deleteRE = new javax.swing.JButton();
        btn_clearRE = new javax.swing.JButton();
        txt_addressRE = new javax.swing.JTextField();
        txt_mobileRE = new javax.swing.JTextField();
        cmb_roomNORE = new javax.swing.JComboBox<>();
        txt_amount1RE = new javax.swing.JTextField();
        lbl_roomNo13 = new javax.swing.JLabel();
        lbl_roomNo11 = new javax.swing.JLabel();
        lbl_roomNo12 = new javax.swing.JLabel();
        lbl_roomNo14 = new javax.swing.JLabel();
        lbl_roomNo15 = new javax.swing.JLabel();
        date_checkInRE = new com.toedter.calendar.JDateChooser();
        lbl_roomNo16 = new javax.swing.JLabel();
        date_checkOutRE = new com.toedter.calendar.JDateChooser();
        lbl_roomNo17 = new javax.swing.JLabel();
        cmb_bedTypeRE = new javax.swing.JComboBox<>();
        lbl_roomNo18 = new javax.swing.JLabel();
        txt_emailRE = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_reservation = new javax.swing.JTable();
        btn_fetch = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_generateREPORT = new javax.swing.JButton();
        txt_resIdREPORT = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_monthlyIncomeREPORTS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(144, 122, 79));
        jPanel3.setPreferredSize(new java.awt.Dimension(1500, 900));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_panel.setBackground(new java.awt.Color(144, 122, 79));
        side_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_roomBTN.setBackground(new java.awt.Color(216, 205, 187));
        pnl_roomBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_roomBTNMouseClicked(evt);
            }
        });
        pnl_roomBTN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Manage Rooms");
        pnl_roomBTN.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        side_panel.add(pnl_roomBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 350, 80));

        pnl_cusBTN.setBackground(new java.awt.Color(216, 205, 187));
        pnl_cusBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_cusBTNMouseClicked(evt);
            }
        });
        pnl_cusBTN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Manage Customers");
        pnl_cusBTN.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        side_panel.add(pnl_cusBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 350, 80));

        pnl_resBTN.setBackground(new java.awt.Color(216, 205, 187));
        pnl_resBTN.setPreferredSize(new java.awt.Dimension(350, 80));
        pnl_resBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_resBTNMouseClicked(evt);
            }
        });
        pnl_resBTN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Manage Reservations");
        pnl_resBTN.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        side_panel.add(pnl_resBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        pnl_homeBTN.setBackground(new java.awt.Color(216, 205, 187));
        pnl_homeBTN.setPreferredSize(new java.awt.Dimension(350, 80));
        pnl_homeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_homeBTNMouseClicked(evt);
            }
        });
        pnl_homeBTN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Home");
        pnl_homeBTN.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        side_panel.add(pnl_homeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/W new.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(45, 20));
        side_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 250, 80));

        pnl_reportsBTN1.setBackground(new java.awt.Color(216, 205, 187));
        pnl_reportsBTN1.setPreferredSize(new java.awt.Dimension(350, 80));
        pnl_reportsBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_reportsBTN1MouseClicked(evt);
            }
        });
        pnl_reportsBTN1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setText("Reports");
        pnl_reportsBTN1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        side_panel.add(pnl_reportsBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        jPanel3.add(side_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 900));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_SysDate.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 18)); // NOI18N
        lbl_SysDate.setForeground(new java.awt.Color(144, 122, 79));
        lbl_SysDate.setText("jLabel12");
        jPanel7.add(lbl_SysDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 190, 40));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/dash.png"))); // NOI18N
        jLabel8.setText("Dashboard");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 870));

        jTabbedPane2.addTab("Home", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(144, 122, 79));
        jLabel6.setText("Manage Rooms");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lbl_roomNo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo.setText("Room No :");
        jPanel8.add(lbl_roomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        lbl_rID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_rID.setForeground(new java.awt.Color(144, 122, 79));
        lbl_rID.setText("R003");
        jPanel8.add(lbl_rID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        lbl_roomType.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomType.setText("Room Type");
        jPanel8.add(lbl_roomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        cmb_roomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non AC" }));
        jPanel8.add(cmb_roomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 160, -1));

        lbl_bedType.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_bedType.setText("Bed Type");
        jPanel8.add(lbl_bedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        cmb_bedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        jPanel8.add(cmb_bedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 160, -1));

        lbl_amount.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_amount.setText("Amount");
        jPanel8.add(lbl_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });
        jPanel8.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 160, -1));

        btn_add.setBackground(new java.awt.Color(144, 122, 79));
        btn_add.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel8.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 170, 50));

        btn_delete.setBackground(new java.awt.Color(144, 122, 79));
        btn_delete.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel8.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 170, 50));

        btn_clear.setBackground(new java.awt.Color(144, 122, 79));
        btn_clear.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel8.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 170, 50));

        btn_edit.setBackground(new java.awt.Color(144, 122, 79));
        btn_edit.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel8.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 170, 50));

        tbl_room.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Room Type", "Bed Type", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_roomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_room);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 1000, 470));

        jTabbedPane2.addTab("Rooms", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(144, 122, 79));
        jLabel7.setText("Manage Customers");
        jLabel7.setToolTipText("");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lbl_roomNo2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo2.setText("NIC");
        jPanel9.add(lbl_roomNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        txt_nic.setForeground(new java.awt.Color(144, 122, 79));
        txt_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicActionPerformed(evt);
            }
        });
        jPanel9.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, -1));

        lbl_roomNo1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo1.setText("Name");
        jPanel9.add(lbl_roomNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        txt_cusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cusNameActionPerformed(evt);
            }
        });
        jPanel9.add(txt_cusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 220, -1));

        btn_addCustomer.setBackground(new java.awt.Color(144, 122, 79));
        btn_addCustomer.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_addCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btn_addCustomer.setText("Add");
        btn_addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addCustomerActionPerformed(evt);
            }
        });
        jPanel9.add(btn_addCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, 50));

        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Name", "Address", "Mobile", "Gender", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_customerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_customer);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 1030, -1));

        btn_editCustomer.setBackground(new java.awt.Color(144, 122, 79));
        btn_editCustomer.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_editCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btn_editCustomer.setText("Edit");
        btn_editCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editCustomerActionPerformed(evt);
            }
        });
        jPanel9.add(btn_editCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 170, 50));

        btn_deleteCustomer.setBackground(new java.awt.Color(144, 122, 79));
        btn_deleteCustomer.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_deleteCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteCustomer.setText("Delete");
        btn_deleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteCustomerActionPerformed(evt);
            }
        });
        jPanel9.add(btn_deleteCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 170, 50));

        btn_clearCustomer.setBackground(new java.awt.Color(144, 122, 79));
        btn_clearCustomer.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_clearCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearCustomer.setText("Clear");
        btn_clearCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearCustomerActionPerformed(evt);
            }
        });
        jPanel9.add(btn_clearCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 170, 50));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel9.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 250, -1));

        cmb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel9.add(cmb_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 250, -1));

        lbl_roomNo5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo5.setText("Gender");
        jPanel9.add(lbl_roomNo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        lbl_roomNo3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo3.setText("Email");
        jPanel9.add(lbl_roomNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        txt_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mobileActionPerformed(evt);
            }
        });
        jPanel9.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 220, -1));

        txt_cusAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cusAddressActionPerformed(evt);
            }
        });
        jPanel9.add(txt_cusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 210, -1));

        lbl_roomNo4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo4.setText("Address");
        jPanel9.add(lbl_roomNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        lbl_roomNo6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo6.setText("Mobile");
        jPanel9.add(lbl_roomNo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jTabbedPane2.addTab("Customers", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel10ComponentShown(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(144, 122, 79));
        jLabel9.setText("Manage Reservations");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbl_roomNo7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo7.setText("Reservation ID :");
        jPanel10.add(lbl_roomNo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lbl_reID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_reID.setForeground(new java.awt.Color(144, 122, 79));
        lbl_reID.setText("RE003");
        jPanel10.add(lbl_reID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        lbl_roomNo8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo8.setText("Name");
        jPanel10.add(lbl_roomNo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        txt_nameRE.setBackground(new java.awt.Color(204, 204, 204));
        txt_nameRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameREActionPerformed(evt);
            }
        });
        jPanel10.add(txt_nameRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 210, -1));

        lbl_roomNo9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo9.setText("NIC");
        jPanel10.add(lbl_roomNo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        txt_nicRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicREActionPerformed(evt);
            }
        });
        jPanel10.add(txt_nicRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 210, -1));

        lbl_roomNo10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo10.setText("Room type");
        jPanel10.add(lbl_roomNo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        cmb_roomTypeRE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_roomTypeREItemStateChanged(evt);
            }
        });
        cmb_roomTypeRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_roomTypeREActionPerformed(evt);
            }
        });
        jPanel10.add(cmb_roomTypeRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 210, -1));

        btn_addRE.setBackground(new java.awt.Color(144, 122, 79));
        btn_addRE.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_addRE.setForeground(new java.awt.Color(255, 255, 255));
        btn_addRE.setText("Add");
        btn_addRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addREActionPerformed(evt);
            }
        });
        jPanel10.add(btn_addRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 170, 50));

        btn_editRE.setBackground(new java.awt.Color(144, 122, 79));
        btn_editRE.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_editRE.setForeground(new java.awt.Color(255, 255, 255));
        btn_editRE.setText("Edit");
        btn_editRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editREActionPerformed(evt);
            }
        });
        jPanel10.add(btn_editRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 170, 50));

        btn_deleteRE.setBackground(new java.awt.Color(144, 122, 79));
        btn_deleteRE.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_deleteRE.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteRE.setText("Delete");
        btn_deleteRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteREActionPerformed(evt);
            }
        });
        jPanel10.add(btn_deleteRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 170, 50));

        btn_clearRE.setBackground(new java.awt.Color(144, 122, 79));
        btn_clearRE.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_clearRE.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearRE.setText("Clear");
        btn_clearRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearREActionPerformed(evt);
            }
        });
        jPanel10.add(btn_clearRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 170, 50));

        txt_addressRE.setBackground(new java.awt.Color(204, 204, 204));
        txt_addressRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressREActionPerformed(evt);
            }
        });
        jPanel10.add(txt_addressRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 210, -1));

        txt_mobileRE.setBackground(new java.awt.Color(204, 204, 204));
        txt_mobileRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mobileREActionPerformed(evt);
            }
        });
        jPanel10.add(txt_mobileRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, -1));

        cmb_roomNORE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_roomNOREActionPerformed(evt);
            }
        });
        jPanel10.add(cmb_roomNORE, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 210, -1));

        txt_amount1RE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amount1REActionPerformed(evt);
            }
        });
        jPanel10.add(txt_amount1RE, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 210, -1));

        lbl_roomNo13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo13.setText("Amount");
        jPanel10.add(lbl_roomNo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, -1, -1));

        lbl_roomNo11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo11.setText("Room NO");
        jPanel10.add(lbl_roomNo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        lbl_roomNo12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo12.setText("Mobile");
        jPanel10.add(lbl_roomNo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        lbl_roomNo14.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo14.setText("Address");
        jPanel10.add(lbl_roomNo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        lbl_roomNo15.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo15.setText("Check in");
        jPanel10.add(lbl_roomNo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        date_checkInRE.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_checkInREPropertyChange(evt);
            }
        });
        jPanel10.add(date_checkInRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 210, -1));

        lbl_roomNo16.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo16.setText("Check out");
        jPanel10.add(lbl_roomNo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        date_checkOutRE.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_checkOutREPropertyChange(evt);
            }
        });
        jPanel10.add(date_checkOutRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 210, -1));

        lbl_roomNo17.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo17.setText("Bed Type");
        jPanel10.add(lbl_roomNo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        cmb_bedTypeRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_bedTypeREActionPerformed(evt);
            }
        });
        jPanel10.add(cmb_bedTypeRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 210, -1));

        lbl_roomNo18.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_roomNo18.setText("Email");
        jPanel10.add(lbl_roomNo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        txt_emailRE.setBackground(new java.awt.Color(204, 204, 204));
        txt_emailRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailREActionPerformed(evt);
            }
        });
        jPanel10.add(txt_emailRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 210, -1));

        tbl_reservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation ID", "Customer NIC", "Room ID", "Checkin Date", "Checkout date", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_reservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_reservationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_reservation);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 1010, 360));

        btn_fetch.setBackground(new java.awt.Color(144, 122, 79));
        btn_fetch.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btn_fetch.setForeground(new java.awt.Color(255, 255, 255));
        btn_fetch.setText("Fetch user data");
        btn_fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fetchActionPerformed(evt);
            }
        });
        jPanel10.add(btn_fetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 140, 30));

        jTabbedPane2.addTab("Reservations", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(144, 122, 79));
        jLabel11.setText("Reports");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(144, 122, 79));
        jLabel16.setText("Generate invoice");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel17.setText("Reservation ID");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btn_generateREPORT.setBackground(new java.awt.Color(144, 122, 79));
        btn_generateREPORT.setForeground(new java.awt.Color(255, 255, 255));
        btn_generateREPORT.setText("Generate");
        btn_generateREPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateREPORTActionPerformed(evt);
            }
        });
        jPanel4.add(btn_generateREPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 140, 40));
        jPanel4.add(txt_resIdREPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, -1));

        jPanel11.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 420, 210));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(144, 122, 79));
        jLabel18.setText("Generate Monthly Income");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btn_monthlyIncomeREPORTS.setBackground(new java.awt.Color(144, 122, 79));
        btn_monthlyIncomeREPORTS.setForeground(new java.awt.Color(255, 255, 255));
        btn_monthlyIncomeREPORTS.setText("Generate");
        btn_monthlyIncomeREPORTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monthlyIncomeREPORTSActionPerformed(evt);
            }
        });
        jPanel5.add(btn_monthlyIncomeREPORTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, 40));

        jPanel11.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 420, 210));

        jTabbedPane2.addTab("Reports", jPanel11);

        jPanel3.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1150, 900));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_roomBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_roomBTNMouseClicked
        jTabbedPane2.setSelectedIndex(1);
        pnl_roomBTN.setBackground(Color.WHITE);
        pnl_cusBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_resBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_homeBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_reportsBTN1.setBackground(Color.decode("#D8CDBB"));
    }//GEN-LAST:event_pnl_roomBTNMouseClicked

    private void pnl_cusBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cusBTNMouseClicked
        jTabbedPane2.setSelectedIndex(2);
        pnl_roomBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_cusBTN.setBackground(Color.WHITE);
        pnl_resBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_homeBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_reportsBTN1.setBackground(Color.decode("#D8CDBB"));
    }//GEN-LAST:event_pnl_cusBTNMouseClicked

    private void txt_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicActionPerformed

    private void txt_cusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cusNameActionPerformed

    private void btn_addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addCustomerActionPerformed

        CustomerModel customerModel1 = new CustomerModel();
String nic = txt_nic.getText().trim();
String cusName = txt_cusName.getText().trim();
String cusAddress = txt_cusAddress.getText().trim();
String mobileText = txt_mobile.getText().trim();
String gender = cmb_gender.getSelectedItem().toString();
String email = txt_email.getText().trim();

// Validate input
if (nic.isEmpty() || cusName.isEmpty() || cusAddress.isEmpty() || mobileText.isEmpty() || email.isEmpty()) {
    // Display an error message if any required field is empty
    JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
} else {
    try {
        // Check if mobileText is a valid integer
        int mobile = Integer.parseInt(mobileText);

        // If all validations pass, proceed with adding the customer
        customerModel1.setCustomer_nic(nic);
        customerModel1.setCustomer_name(cusName);
        customerModel1.setCustomer_adress(cusAddress);
        customerModel1.setCustomer_mobile(mobile);
        customerModel1.setCustomer_gender(gender);
        customerModel1.setCustomer_email(email);

        customerController1.addCustomer(customerModel1);

        DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();
        model.setRowCount(0);

        customerController1.loadCustomer(tbl_customer, customerModel1);
    } catch (NumberFormatException e) {
        // Display an error message if mobileText is not a valid integer
        JOptionPane.showMessageDialog(this, "Please enter a valid mobile number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_btn_addCustomerActionPerformed

    private void tbl_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_customerMouseClicked

        CustomerModel customerModel1 = new CustomerModel();
        customerController1.viewCustomer(customerModel1, tbl_customer, txt_nic, txt_cusName, txt_cusAddress, txt_mobile, cmb_gender, txt_email);
        btn_addCustomer.setEnabled(false);

    }//GEN-LAST:event_tbl_customerMouseClicked

    private void btn_editCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editCustomerActionPerformed

        CustomerModel customerModel1 = new CustomerModel();
        customerModel1.setCustomer_name(txt_cusName.getText());
        customerModel1.setCustomer_adress(txt_cusAddress.getText());
        customerModel1.setCustomer_mobile(Integer.parseInt(txt_mobile.getText()));
        customerModel1.setCustomer_gender(cmb_gender.getSelectedItem().toString());
        customerModel1.setCustomer_email(txt_email.getText());

        customerController1.editCustomer(customerModel1, txt_nic.getText(), txt_cusName, txt_cusAddress, txt_mobile, cmb_gender, txt_email);
        DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();
        model.setRowCount(0); 

        customerController1.loadCustomer(tbl_customer, customerModel1);
        
    }//GEN-LAST:event_btn_editCustomerActionPerformed

    private void btn_deleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteCustomerActionPerformed

        CustomerModel customerModel1 = new CustomerModel();
        customerController1.deleteCustomer(customerModel1, txt_nic.getText());
        
        DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();
        model.setRowCount(0); 

        customerController1.loadCustomer(tbl_customer, customerModel1);
    }//GEN-LAST:event_btn_deleteCustomerActionPerformed

    private void btn_clearCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearCustomerActionPerformed
        txt_cusName.setText("");
        txt_nic.setText("");
        txt_cusAddress.setText("");
        txt_mobile.setText("");
        txt_email.setText("");
        cmb_gender.setSelectedIndex(0);
        btn_addCustomer.setEnabled(true);
    }//GEN-LAST:event_btn_clearCustomerActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mobileActionPerformed

    private void txt_cusAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cusAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cusAddressActionPerformed

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amountActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
    String roomType = cmb_roomType.getSelectedItem().toString();
    String bedType = cmb_bedType.getSelectedItem().toString();
    String amountText = txt_amount.getText();

    // Validate input
    if (roomType.isEmpty() || bedType.isEmpty() || amountText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // Check if the amount is a valid integer
    int roomAmount;
    try {
        roomAmount = Integer.parseInt(amountText);
    } catch (NumberFormatException e) {
        // Display an error message if the amount is not a valid integer
        JOptionPane.showMessageDialog(this, "Please enter a valid room amount.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // If all validations pass, proceed with adding the room
    RoomModel roomModel1 = new RoomModel();
    roomModel1.setRoom_type(roomType);
    roomModel1.setBed_type(bedType);
    roomModel1.setRoom_amount(roomAmount);

    roomController1.addRoom(roomModel1, lbl_rID.getText());
    
    roomController1.autoID(roomModel1, lbl_rID);
   
    DefaultTableModel model = (DefaultTableModel) tbl_room.getModel();
    model.setRowCount(0);

        roomController1.loadRoom(tbl_room, roomModel1);
        

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        RoomModel roomModel1 = new RoomModel();
        roomController1.deleteRoom(roomModel1 , lbl_rID.getText());
        roomController1.autoID(roomModel1, lbl_rID);
        
        DefaultTableModel model = (DefaultTableModel) tbl_room.getModel();
        model.setRowCount(0); 

        roomController1.loadRoom(tbl_room, roomModel1);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        btn_add.setEnabled(true);
        cmb_bedType.setSelectedIndex(0);
        cmb_roomType.setSelectedIndex(0);
        txt_amount.setText("");
        
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed

        RoomModel roomModel1 = new RoomModel();
        roomModel1.setRoom_type(cmb_roomType.getSelectedItem().toString());
        roomModel1.setBed_type(cmb_bedType.getSelectedItem().toString());
        roomModel1.setRoom_amount(Integer.parseInt(txt_amount.getText()));

        roomController1.editRoom(roomModel1 , lbl_rID.getText(), cmb_roomType, cmb_bedType, txt_amount);
        DefaultTableModel model = (DefaultTableModel) tbl_room.getModel();
        model.setRowCount(0); 

        roomController1.loadRoom(tbl_room, roomModel1);

    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_roomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_roomMouseClicked
        RoomModel roomModel1 = new RoomModel();
        roomController1.viewRoom(roomModel1, tbl_room, lbl_rID, cmb_roomType, cmb_bedType, txt_amount);
        btn_add.setEnabled(false);

    }//GEN-LAST:event_tbl_roomMouseClicked

    private void pnl_resBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_resBTNMouseClicked
        jTabbedPane2.setSelectedIndex(3);
        pnl_roomBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_cusBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_resBTN.setBackground(Color.WHITE);
        pnl_homeBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_reportsBTN1.setBackground(Color.decode("#D8CDBB"));
    }//GEN-LAST:event_pnl_resBTNMouseClicked

    private void pnl_homeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_homeBTNMouseClicked
        jTabbedPane2.setSelectedIndex(0);
        pnl_roomBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_cusBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_resBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_reportsBTN1.setBackground(Color.decode("#D8CDBB"));
        pnl_homeBTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_pnl_homeBTNMouseClicked

    private void txt_nameREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameREActionPerformed

    private void txt_nicREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nicREActionPerformed

    private void btn_addREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addREActionPerformed
       // Validate date inputs
    Date checkinDate = date_checkInRE.getDate();
    Date checkoutDate = date_checkOutRE.getDate();

    if (checkinDate == null || checkoutDate == null) {
        JOptionPane.showMessageDialog(this, "Please enter the values.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    } else {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateString1 = dateFormat.format(checkinDate);
        String dateString2 = dateFormat.format(checkoutDate);

    // Validate amount input
    String amountText = txt_amount1RE.getText();
    if (amountText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the amount.", "Validation Error", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
            int amount = Integer.parseInt(amountText);

            // Check if amount is a positive integer
            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "Amount must be a positive integer.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            } else {
                // If all validations pass, proceed with adding the reservation
                reController1.addReservation(lbl_reID.getText(), txt_nicRE.getText(), cmb_roomNORE.getSelectedItem().toString(), dateString1, dateString2, amount);
                ReservationModel reModel1 = new ReservationModel();
                reController1.autoID(reModel1, lbl_reID);

                DefaultTableModel model = (DefaultTableModel) tbl_reservation.getModel();
                model.setRowCount(0);

                reController1.loadReservation(tbl_reservation, reModel1);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid amount.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
    
    }//GEN-LAST:event_btn_addREActionPerformed

    private void btn_editREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editREActionPerformed
        ReservationModel reservationModel1 = new ReservationModel();
        
        reservationModel1.setId(lbl_reID.toString());
        reservationModel1.setCustomer_nic(txt_nicRE.toString());
        reservationModel1.setRoom_roomID(cmb_roomNORE.getSelectedItem().toString());
        reservationModel1.setCheckin(date_checkInRE.getDate());
        reservationModel1.setCheckout(date_checkOutRE.getDate());
        int amount = Integer.parseInt(txt_amount1RE.getText());
        reservationModel1.setAmount(amount);

        
        reController1.editReservation(reservationModel1);
        
         DefaultTableModel model = (DefaultTableModel) tbl_reservation.getModel();
        model.setRowCount(0); 

        reController1.loadReservation(tbl_reservation, reservationModel1);

        
        
    }//GEN-LAST:event_btn_editREActionPerformed

    private void btn_deleteREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteREActionPerformed
        
        ReservationModel reservationModel1 = new ReservationModel();
        reController1.deleteReservation(reservationModel1 , lbl_reID.getText());
        reController1.autoID(reservationModel1, lbl_reID);
        
        DefaultTableModel model = (DefaultTableModel) tbl_reservation.getModel();
        model.setRowCount(0); 

        reController1.loadReservation(tbl_reservation, reservationModel1);
        
    }//GEN-LAST:event_btn_deleteREActionPerformed

    private void btn_clearREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearREActionPerformed
        isAddReservation = true;
        btn_addRE.setEnabled(true);
        
        txt_nicRE.setText("");
        txt_nameRE.setText("");
        txt_addressRE.setText("");
        txt_mobileRE.setText("");
        txt_emailRE.setText("");
        cmb_bedTypeRE.setSelectedIndex(0);
        cmb_roomTypeRE.setSelectedIndex(0);
        cmb_roomNORE.setSelectedIndex(0);
 
       
        
          
    }//GEN-LAST:event_btn_clearREActionPerformed

    private void txt_addressREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressREActionPerformed

    private void txt_mobileREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mobileREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mobileREActionPerformed

    private void txt_amount1REActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amount1REActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amount1REActionPerformed

    private void txt_emailREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailREActionPerformed

    private void tbl_reservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_reservationMouseClicked
              isAddReservation = false;
              
              int selectedRow = tbl_reservation.getSelectedRow();
              String reservationId = tbl_reservation.getValueAt(selectedRow, 0).toString();
              ReservationModel resModel1 = reController1.getReservationDataAll(reservationId);
              
              txt_nameRE.setText(resModel1.getCustomer_name());
              txt_addressRE.setText(resModel1.getCustomer_address());
              txt_nicRE.setText(resModel1.getCustomer_nic());
              txt_mobileRE.setText(String.valueOf(resModel1.getCustomer_mobile()));
              lbl_reID.setText(resModel1.getId());
              txt_emailRE.setText(resModel1.getCustomer_email());
              
              
              cmb_roomTypeRE.setSelectedItem(resModel1.getRoom_roomType());
              cmb_bedTypeRE.setSelectedItem(resModel1.getRoom_bedType());
              cmb_roomNORE.setSelectedItem(resModel1.getRoom_roomID());
              
              date_checkInRE.setDate(resModel1.getCheckin());
              date_checkOutRE.setDate(resModel1.getCheckout());
              
               btn_addRE.setEnabled(false);
        
    }//GEN-LAST:event_tbl_reservationMouseClicked

    private void cmb_roomTypeREItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_roomTypeREItemStateChanged
        
    }//GEN-LAST:event_cmb_roomTypeREItemStateChanged

    private void cmb_roomTypeREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_roomTypeREActionPerformed
        loadRoomsRE();
    }//GEN-LAST:event_cmb_roomTypeREActionPerformed

    private void loadRoomsRE(){
        try {
            cmb_roomNORE.removeAllItems();
            if(cmb_bedTypeRE.getSelectedItem() != null && cmb_roomTypeRE.getSelectedItem() != null){
                String bedType = cmb_bedTypeRE.getSelectedItem().toString();
                String roomType = cmb_roomTypeRE.getSelectedItem().toString();

                roomsRE = roomController1.getRoomsByType(roomType, bedType);

                Iterator it = roomsRE.iterator();
                while (it.hasNext()){
                    RoomModel rModel = (RoomModel)it.next();
                    cmb_roomNORE.addItem(rModel.getRoom_id());
                }
            }
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    private void cmb_bedTypeREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_bedTypeREActionPerformed
        loadRoomsRE();
    }//GEN-LAST:event_cmb_bedTypeREActionPerformed

    private void date_checkInREPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_checkInREPropertyChange
        
        if(evt.getPropertyName().equals("date")){
            date_checkOutRE.setCalendar(null);
            var localDate = date_checkInRE.getDate().toInstant()
                                .atZone(ZoneId.systemDefault()).toLocalDateTime().plusDays(1);
                Date date = java.util.Date.from(localDate
              .atZone(ZoneId.systemDefault())
              .toInstant());
                date_checkOutRE.setMinSelectableDate(date);
            calculateAmount();
        }
            
    }//GEN-LAST:event_date_checkInREPropertyChange

    private void date_checkOutREPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_checkOutREPropertyChange
        if(evt.getPropertyName().equals("date")){
            calculateAmount();
        }
    }//GEN-LAST:event_date_checkOutREPropertyChange

    private void cmb_roomNOREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_roomNOREActionPerformed
        calculateAmount();
    }//GEN-LAST:event_cmb_roomNOREActionPerformed

    private void btn_fetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fetchActionPerformed

        CustomerModel cModel1 = reController1.fetchData(txt_nicRE.getText());
        txt_nameRE.setText(cModel1.getCustomer_name());
        txt_addressRE.setText(cModel1.getCustomer_adress());
        txt_emailRE.setText(cModel1.getCustomer_email());
        txt_mobileRE.setText(String.valueOf(cModel1.getCustomer_mobile()));

    }//GEN-LAST:event_btn_fetchActionPerformed

    private void jPanel10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel10ComponentShown
        txt_nameRE.setEditable(false);
        txt_addressRE.setEditable(false);
        txt_emailRE.setEditable(false);
        txt_mobileRE.setEditable(false);
        
    }//GEN-LAST:event_jPanel10ComponentShown

    private void pnl_reportsBTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_reportsBTN1MouseClicked
        jTabbedPane2.setSelectedIndex(4);
        pnl_roomBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_reportsBTN1.setBackground(Color.WHITE);
        pnl_cusBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_resBTN.setBackground(Color.decode("#D8CDBB"));
        pnl_homeBTN.setBackground(Color.decode("#D8CDBB"));
    }//GEN-LAST:event_pnl_reportsBTN1MouseClicked

    private void btn_generateREPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateREPORTActionPerformed
           
          try {
    // Get the value from the JTextField
    String reservationId = txt_resIdREPORT.getText();

    // Load the JasperDesign from the JRXML file
    JasperDesign jasperDesign = JRXmlLoader.load("/Users/tharaka/EAD CW/HotelManagementSystem/src/view/report1.jrxml");


    // Compile the JasperReport
    JasperReport report = JasperCompileManager.compileReport(jasperDesign);

    // Create a parameter map and set the "reservation_id" parameter
    Map<String, Object> parameters = new HashMap<>();
    parameters.put("Res_IDDDD", reservationId);

    // Fill the report with parameters
    JasperPrint print = JasperFillManager.fillReport(report, parameters, MyDbConnection.getMyDBConnection());

    // View the report
    JasperViewer.viewReport(print);
} catch (JRException ex) {
    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
}

              
    }//GEN-LAST:event_btn_generateREPORTActionPerformed

    private void btn_monthlyIncomeREPORTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monthlyIncomeREPORTSActionPerformed
        
            try {
                      
            JasperDesign jasperDesign = JRXmlLoader.load("/Users/tharaka/EAD CW/HotelManagementSystem/src/view/report3.jrxml");
//            JRDesignQuery designQuery = new JRDesignQuery();
//            designQuery.setText("SELECT MONTH(checkin_date) AS reservation_month, COUNT(*) AS reservation_count\n" +
//            "FROM tbl_reservation\n" +
//            "GROUP BY reservation_month;");
//            jasperDesign.setQuery(designQuery);
            JasperReport report = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint print  = JasperFillManager.fillReport(report, null, MyDbConnection.getMyDBConnection());
            JasperViewer.viewReport(print);
            
        
        } catch (JRException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
        
    }//GEN-LAST:event_btn_monthlyIncomeREPORTSActionPerformed

    private void calculateAmount(){
        if(date_checkInRE.getDate() != null && date_checkOutRE.getDate() != null){
            LocalDate start = date_checkInRE.getDate().toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate();
                  LocalDate end   = date_checkOutRE.getDate().toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate();

            long diffInDays = ChronoUnit.DAYS.between(start, end);
            
            Iterator it = roomsRE.iterator();
            while (it.hasNext()){
                RoomModel rModel = (RoomModel)it.next();
                if(cmb_roomNORE.getSelectedItem() != null){
                if(rModel.getRoom_id().equals(cmb_roomNORE.getSelectedItem().toString())){
                    txt_amount1RE.setText(String.valueOf(diffInDays * rModel.getRoom_amount()));
                }
                }
            }
        }
        
    }
    
    private void initializeTimer() {
    // Create a timer to update the label every second (1000 milliseconds)
    Timer timer = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            // Get the current date and time
            Date currentDate = new Date();

            // Define a date format
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

            // Format the date as a string
            String formattedDate = dateFormat.format(currentDate);

            // Set the label's text to the formatted date and time
            lbl_SysDate.setText(formattedDate);
        }
    });

    // Start the timer
    timer.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addCustomer;
    private javax.swing.JButton btn_addRE;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_clearCustomer;
    private javax.swing.JButton btn_clearRE;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_deleteCustomer;
    private javax.swing.JButton btn_deleteRE;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_editCustomer;
    private javax.swing.JButton btn_editRE;
    private javax.swing.JButton btn_fetch;
    private javax.swing.JButton btn_generateREPORT;
    private javax.swing.JButton btn_monthlyIncomeREPORTS;
    private javax.swing.JComboBox<String> cmb_bedType;
    private javax.swing.JComboBox<String> cmb_bedTypeRE;
    private javax.swing.JComboBox<String> cmb_gender;
    private javax.swing.JComboBox<String> cmb_roomNORE;
    private javax.swing.JComboBox<String> cmb_roomType;
    private javax.swing.JComboBox<String> cmb_roomTypeRE;
    private com.toedter.calendar.JDateChooser date_checkInRE;
    private com.toedter.calendar.JDateChooser date_checkOutRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_SysDate;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_bedType;
    private javax.swing.JLabel lbl_rID;
    private javax.swing.JLabel lbl_reID;
    private javax.swing.JLabel lbl_roomNo;
    private javax.swing.JLabel lbl_roomNo1;
    private javax.swing.JLabel lbl_roomNo10;
    private javax.swing.JLabel lbl_roomNo11;
    private javax.swing.JLabel lbl_roomNo12;
    private javax.swing.JLabel lbl_roomNo13;
    private javax.swing.JLabel lbl_roomNo14;
    private javax.swing.JLabel lbl_roomNo15;
    private javax.swing.JLabel lbl_roomNo16;
    private javax.swing.JLabel lbl_roomNo17;
    private javax.swing.JLabel lbl_roomNo18;
    private javax.swing.JLabel lbl_roomNo2;
    private javax.swing.JLabel lbl_roomNo3;
    private javax.swing.JLabel lbl_roomNo4;
    private javax.swing.JLabel lbl_roomNo5;
    private javax.swing.JLabel lbl_roomNo6;
    private javax.swing.JLabel lbl_roomNo7;
    private javax.swing.JLabel lbl_roomNo8;
    private javax.swing.JLabel lbl_roomNo9;
    private javax.swing.JLabel lbl_roomType;
    private javax.swing.JPanel pnl_cusBTN;
    private javax.swing.JPanel pnl_homeBTN;
    private javax.swing.JPanel pnl_reportsBTN1;
    private javax.swing.JPanel pnl_resBTN;
    private javax.swing.JPanel pnl_roomBTN;
    private javax.swing.JPanel side_panel;
    private javax.swing.JTable tbl_customer;
    private javax.swing.JTable tbl_reservation;
    private javax.swing.JTable tbl_room;
    private javax.swing.JTextField txt_addressRE;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_amount1RE;
    private javax.swing.JTextField txt_cusAddress;
    private javax.swing.JTextField txt_cusName;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailRE;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_mobileRE;
    private javax.swing.JTextField txt_nameRE;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_nicRE;
    private javax.swing.JTextField txt_resIdREPORT;
    // End of variables declaration//GEN-END:variables
}
